#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.service.enabled -}}

{{ $tcpPorts := dict }}
{{ $udpPorts := dict }}
{{- range $name, $config := .Values.ports }}
  {{- if eq (toString $config.protocol) "UDP" }}
    {{ $_ := set $udpPorts $name $config }}
  {{- else }}
    {{ $_ := set $tcpPorts $name $config }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: List
items:
{{- if  $tcpPorts }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "traefik.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ template "traefik.name" . }}
        helm.sh/chart: {{ template "traefik.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- $type := default "LoadBalancer" .Values.service.type }}
      type: {{ $type }}
      {{- with .Values.service.spec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      selector:
        app.kubernetes.io/name: {{ template "traefik.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
      {{- range $name, $config := $tcpPorts }}
      {{- if $config.expose }}
      - port: {{ default $config.port $config.exposedPort }}
        name: {{ $name }}
        targetPort: {{ $name | quote }}
        protocol: {{ default "TCP" $config.protocol | quote }}
        {{- if $config.nodePort }}
        nodePort: {{ $config.nodePort }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if eq $type "LoadBalancer" }}
      {{- with .Values.service.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
      {{- end -}}
      {{- with .Values.service.externalIPs }}
      externalIPs:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
{{- end }}

{{- if  $udpPorts }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "traefik.fullname" . }}-udp
      labels:
        app.kubernetes.io/name: {{ template "traefik.name" . }}
        helm.sh/chart: {{ template "traefik.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- with .Values.service.annotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- $type := default "LoadBalancer" .Values.service.type }}
      type: {{ $type }}
      {{- with .Values.service.spec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      selector:
        app.kubernetes.io/name: {{ template "traefik.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
      {{- range $name, $config := $udpPorts }}
      {{- if $config.expose }}
      - port: {{ default $config.port $config.exposedPort }}
        name: {{ $name }}
        targetPort: {{ $name | quote }}
        protocol: {{ default "UDP" $config.protocol | quote }}
        {{- if $config.nodePort }}
        nodePort: {{ $config.nodePort }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if eq $type "LoadBalancer" }}
      {{- with .Values.service.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
      {{- end -}}
      {{- with .Values.service.externalIPs }}
      externalIPs:
      {{- toYaml . | nindent 6 }}
      {{- end -}}
{{- end }}
{{- end -}}
