# RC for svc1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: docker.io/patrickeasters/example-web-service
        env:
        - name: APP_SVC
          value: svc1
        ports:
        - containerPort: 8080
          protocol: TCP
---
# Service for svc1
apiVersion: v1
kind: Service
metadata:
  name: mnist-tfboard
  namespace: default
  labels:
    app: mnist-tfboard
spec:
  selector:
    app: svc1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mnist-tfboard
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
        - path: /testpath
          backend:
            serviceName: mnist-tfboard
            servicePort: 8080

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: example-web-app
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /s1
#         backend:
#           serviceName: svc1
#           servicePort: 8080
      # - path: /s2
      #   backend:
      #     serviceName: svc2
      #     servicePort: 8080
      # - path: /
      #   backend:
      #     serviceName: svc3
      #     servicePort: 8080